appId: com.poyka.ripdpi
---
- setOrientation: PORTRAIT
- launchApp:
    stopApp: true
- assertVisible:
    id: "home-screen"
- assertVisible:
    id: "home-mode-primary-local-dpi-bypass"
- tapOn:
    id: "home-mode-primary-local-dpi-bypass"
- assertVisible:
    id: "home-mode-primary-local-dpi-bypass"
- tapOn:
    id: "home-mode-primary-local-dpi-bypass"
- assertVisible:
    id: "home-mode-primary-local-dpi-bypass"
