package com.poyka.ripdpi.diagnostics

import com.poyka.ripdpi.data.ServiceTelemetrySnapshot
import com.poyka.ripdpi.data.diagnostics.TelemetrySampleEntity

internal fun ServiceTelemetrySnapshot.toTelemetrySampleEntity(
    id: String,
    sessionId: String? = null,
    connectionSessionId: String? = null,
    diagnosticsRunId: String? = null,
    diagnosticsStageKey: String? = null,
    activeModeFallback: String,
    connectionStateOverride: String? = null,
    networkType: String,
    publicIp: String?,
    nativeHeapBytes: Long? = null,
    processRssBytes: Long? = null,
    createdAt: Long,
): TelemetrySampleEntity =
    TelemetrySampleEntity(
        id = id,
        sessionId = sessionId,
        connectionSessionId = connectionSessionId,
        diagnosticsRunId = diagnosticsRunId,
        diagnosticsStageKey = diagnosticsStageKey,
        activeMode = mode?.name ?: activeModeFallback,
        connectionState = connectionStateOverride ?: status.name,
        networkType = networkType,
        publicIp = publicIp,
        failureClass = runtimeFieldTelemetry.failureClass?.wireValue,
        telemetryNetworkFingerprintHash = runtimeFieldTelemetry.telemetryNetworkFingerprintHash,
        winningTcpStrategyFamily = runtimeFieldTelemetry.winningTcpStrategyFamily,
        winningQuicStrategyFamily = runtimeFieldTelemetry.winningQuicStrategyFamily,
        proxyRttBand = runtimeFieldTelemetry.proxyRttBand.wireValue,
        resolverRttBand = runtimeFieldTelemetry.resolverRttBand.wireValue,
        proxyRouteRetryCount = runtimeFieldTelemetry.proxyRouteRetryCount,
        tunnelRecoveryRetryCount = runtimeFieldTelemetry.tunnelRecoveryRetryCount,
        resolverId = tunnelTelemetry.resolverId,
        resolverProtocol = tunnelTelemetry.resolverProtocol,
        resolverEndpoint = tunnelTelemetry.resolverEndpoint,
        resolverLatencyMs = tunnelTelemetry.resolverLatencyMs,
        dnsFailuresTotal = tunnelTelemetry.dnsFailuresTotal,
        resolverFallbackActive = tunnelTelemetry.resolverFallbackActive,
        resolverFallbackReason = tunnelTelemetry.resolverFallbackReason,
        networkHandoverClass = tunnelTelemetry.networkHandoverClass,
        networkHandoverState = networkHandoverState,
        proxyTelemetryState = proxyTelemetryStatus.state.wireValue,
        proxyTelemetryMessage = proxyTelemetryStatus.message,
        relayTelemetryState = relayTelemetryStatus.state.wireValue,
        relayTelemetryMessage = relayTelemetryStatus.message,
        warpTelemetryState = warpTelemetryStatus.state.wireValue,
        warpTelemetryMessage = warpTelemetryStatus.message,
        tunnelTelemetryState = tunnelTelemetryStatus.state.wireValue,
        tunnelTelemetryMessage = tunnelTelemetryStatus.message,
        lastFailureClass = proxyTelemetry.lastFailureClass,
        lastFallbackAction = proxyTelemetry.lastFallbackAction,
        txPackets = tunnelStats.txPackets,
        txBytes = tunnelStats.txBytes,
        rxPackets = tunnelStats.rxPackets,
        rxBytes = tunnelStats.rxBytes,
        nativeHeapBytes = nativeHeapBytes,
        processRssBytes = processRssBytes,
        relayProtocolKind = relayTelemetry.protocolKind,
        createdAt = createdAt,
    )
