package com.poyka.ripdpi.core.detection

object DetectionReportFormatter {
    fun format(result: DetectionCheckResult): String =
        buildString {
            appendLine("=== Detection Check Report ===")
            appendLine()
            appendLine("Verdict: ${result.verdict}")
            appendLine()

            appendCategory("GeoIP", result.geoIp)
            appendCategory("Direct Signs", result.directSigns)
            appendCategory("Indirect Signs", result.indirectSigns)
            appendCategory("Location Signals", result.locationSignals)
            appendBypass(result.bypassResult)
            result.dnsLeak?.let { appendCategory("DNS Leak", it) }
            result.webRtcLeak?.let { appendCategory("WebRTC Leak", it) }
            result.tlsFingerprint?.let { appendCategory("TLS Fingerprint", it) }
            result.timingAnalysis?.let { appendCategory("Timing Analysis", it) }

            appendLine("Methodology: ${result.methodologyVersion}")

            val recommendations = DetectionRecommendations.generate(result)
            if (recommendations.isNotEmpty()) {
                appendLine()
                appendLine("--- Recommendations ---")
                for (rec in recommendations) {
                    appendLine("* ${rec.title}: ${rec.description}")
                }
            }

            appendLine()
            appendLine("Generated by RIPDPI Detection Check")
        }

    private fun StringBuilder.appendCategory(
        title: String,
        category: CategoryResult,
    ) {
        appendLine("--- $title ---")
        val status =
            when {
                category.detected -> "DETECTED"
                category.needsReview -> "NEEDS REVIEW"
                else -> "OK"
            }
        appendLine("Status: $status")
        for (finding in category.findings) {
            val prefix =
                when {
                    finding.detected -> "!"
                    finding.needsReview -> "?"
                    else -> "-"
                }
            appendLine("  $prefix ${finding.description}")
        }
        appendLine()
    }

    private fun StringBuilder.appendBypass(bypass: BypassResult) {
        appendLine("--- Bypass ---")
        val status =
            when {
                bypass.detected -> "DETECTED"
                bypass.needsReview -> "NEEDS REVIEW"
                else -> "OK"
            }
        appendLine("Status: $status")
        for (finding in bypass.findings) {
            val prefix =
                when {
                    finding.detected -> "!"
                    finding.needsReview -> "?"
                    else -> "-"
                }
            appendLine("  $prefix ${finding.description}")
        }
        appendLine()
    }
}
