[package]
name = "ripdpi-relay-tls-transports"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ripdpi-relay-mux = { workspace = true }
ripdpi-anytls = { workspace = true }
ripdpi-shadowtls = { workspace = true }
ripdpi-shadowsocks = { workspace = true }
ripdpi-tor = { workspace = true }
ripdpi-trojan = { workspace = true }
ripdpi-mieru = { workspace = true }
ripdpi-network-time = { workspace = true }
ripdpi-ssh = { workspace = true }
ripdpi-vless = { workspace = true }
ripdpi-native-protect = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "sync"] }
tokio-boring = { workspace = true }

[lints]
workspace = true
