[package]
name = "ripdpi-tor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arti-client = { workspace = true }
rustls = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "time"] }
toml = { workspace = true }
tor-rtcompat = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }

[lints]
workspace = true
