[package]
name = "ripdpi-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true }
ripdpi-native-protect = { workspace = true }
russh = { workspace = true }
thiserror = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["net", "rt-multi-thread", "time", "macros", "io-util"] }

[lints]
workspace = true
