package com.poyka.ripdpi.core.detection

import org.junit.Assert.assertTrue
import org.junit.Test

class DetectionReportFormatterTest {
    private fun emptyCategory(name: String) =
        CategoryResult(
            name = name,
            detected = false,
            findings = emptyList(),
        )

    private fun emptyBypass() =
        BypassResult(
            proxyEndpoint = null,
            directIp = null,
            proxyIp = null,
            xrayApiScanResult = null,
            findings = emptyList(),
            detected = false,
        )

    @Test
    fun `report contains verdict`() {
        val result =
            DetectionCheckResult(
                geoIp = emptyCategory("GeoIP"),
                directSigns = emptyCategory("Direct"),
                indirectSigns = emptyCategory("Indirect"),
                locationSignals = emptyCategory("Location"),
                bypassResult = emptyBypass(),
                verdict = Verdict.NOT_DETECTED,
            )
        val report = DetectionReportFormatter.format(result)
        assertTrue(report.contains("Verdict: NOT_DETECTED"))
        assertTrue(report.contains("=== Detection Check Report ==="))
        assertTrue(report.contains("Generated by RIPDPI"))
    }

    @Test
    fun `report contains all sections`() {
        val result =
            DetectionCheckResult(
                geoIp = emptyCategory("GeoIP"),
                directSigns = emptyCategory("Direct"),
                indirectSigns = emptyCategory("Indirect"),
                locationSignals = emptyCategory("Location"),
                bypassResult = emptyBypass(),
                verdict = Verdict.DETECTED,
            )
        val report = DetectionReportFormatter.format(result)
        assertTrue(report.contains("--- GeoIP ---"))
        assertTrue(report.contains("--- Direct Signs ---"))
        assertTrue(report.contains("--- Indirect Signs ---"))
        assertTrue(report.contains("--- Location Signals ---"))
        assertTrue(report.contains("--- Bypass ---"))
    }

    @Test
    fun `report includes findings`() {
        val result =
            DetectionCheckResult(
                geoIp =
                    emptyCategory("GeoIP").copy(
                        findings =
                            listOf(
                                Finding("IP: 1.2.3.4"),
                                Finding("IP belongs to hosting provider: yes", detected = true),
                            ),
                    ),
                directSigns = emptyCategory("Direct"),
                indirectSigns = emptyCategory("Indirect"),
                locationSignals = emptyCategory("Location"),
                bypassResult = emptyBypass(),
                verdict = Verdict.NEEDS_REVIEW,
            )
        val report = DetectionReportFormatter.format(result)
        assertTrue(report.contains("IP: 1.2.3.4"))
        assertTrue(report.contains("! IP belongs to hosting provider: yes"))
    }
}
