#!/usr/bin/env python3
"""Generate the exact R8 boundary required by release Hilt instrumentation."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


GENERATED_COMPONENTS = (
    "DaggerAndroidOrdinaryPhysicalEvidenceTest_HiltComponents_SingletonC.java",
    "AndroidOrdinaryPhysicalEvidenceTest_HiltComponents.java",
)
IMPORT_PATTERN = re.compile(r"^import ([A-Za-z_$][A-Za-z0-9_.$]*);$", re.MULTILINE)
EXCLUDED_PREFIXES = (
    "android.",
    "java.",
    "javax.",
    "org.jetbrains.annotations.",
)
TEST_ONLY_PREFIX = "com.poyka.ripdpi.e2e."
PRODUCTION_PREFIX = "com.poyka.ripdpi."
ORDINARY_SOURCE_FILE = b"AndroidOrdinaryPhysicalEvidenceTest.kt"
BYTECODE_REFERENCE_PATTERN = re.compile(
    r"= (?:InterfaceMethod|Method|Field)ref\s+.*// ([A-Za-z0-9_/$]+)\."
)
HEADER = """# Generated by scripts/ci/generate_release_instrumentation_rules.py.
#
# The release AndroidTest Hilt component is compiled independently from the
# optimized target APK. R8 cannot see its references while shrinking the target,
# so retain only the component's exact binary-link surface. Classes may still
# be obfuscated and rewritten into the test APK by AGP, but member names must
# remain stable because the separately compiled test invokes them by source
# name after target optimization.
#
# Regenerate after compiling :app:hiltJavaCompileGithubFullReleaseAndroidTest.

"""


def component_sources(repo_root: Path) -> list[Path]:
    source_root = (
        repo_root
        / "app/build/generated/hilt/component_sources/githubFullReleaseAndroidTest"
        / "dagger/hilt/android/internal/testing/root"
    )
    paths = [source_root / name for name in GENERATED_COMPONENTS]
    missing = [path for path in paths if not path.is_file()]
    if missing:
        rendered = ", ".join(str(path) for path in missing)
        raise ValueError(
            "release instrumentation Hilt sources are missing; run "
            ":app:hiltJavaCompileGithubFullReleaseAndroidTest first: " + rendered
        )
    return paths


def boundary_classes(repo_root: Path) -> list[str]:
    imports: set[str] = set()
    for path in component_sources(repo_root):
        imports.update(IMPORT_PATTERN.findall(path.read_text(encoding="utf-8")))
    boundary = {
        class_name
        for class_name in imports
        if not class_name.startswith(EXCLUDED_PREFIXES)
        and not class_name.startswith(TEST_ONLY_PREFIX)
    }
    boundary.update(bytecode_boundary_classes(repo_root))
    if len(boundary) < 700:
        raise ValueError(
            f"release instrumentation boundary is suspiciously small: {len(boundary)}"
        )
    return sorted(boundary)


def bytecode_boundary_classes(repo_root: Path) -> set[str]:
    bytecode_root = (
        repo_root
        / "app/build/intermediates/built_in_kotlinc/githubFullReleaseAndroidTest"
        / "compileGithubFullReleaseAndroidTestKotlin/classes/com/poyka/ripdpi/e2e"
    )
    class_files = sorted(
        path
        for path in bytecode_root.glob("*.class")
        if ORDINARY_SOURCE_FILE in path.read_bytes()
    )
    if not class_files:
        raise ValueError(
            "release ordinary instrumentation bytecode is missing; run "
            ":app:hiltJavaCompileGithubFullReleaseAndroidTest first: "
            + str(bytecode_root)
        )
    javap = subprocess.run(
        ["javap", "-verbose", *(str(path) for path in class_files)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    owners = {
        match.group(1).replace("/", ".")
        for match in BYTECODE_REFERENCE_PATTERN.finditer(javap)
    }
    boundary = {
        owner
        for owner in owners
        if owner.startswith(PRODUCTION_PREFIX)
        and not owner.startswith(TEST_ONLY_PREFIX)
    }
    if len(boundary) < 5:
        raise ValueError(
            "release ordinary instrumentation bytecode boundary is suspiciously "
            f"small: {len(boundary)}"
        )
    return boundary


def render_rules(repo_root: Path) -> str:
    lines = [HEADER.rstrip(), ""]
    for class_name in boundary_classes(repo_root):
        lines.append(
            f"-keep,allowoptimization,allowobfuscation class {class_name}"
        )
        lines.append(
            f"-keepclassmembers class {class_name} {{ *; }}"
        )
        lines.append(
            f"-keep,allowoptimization,allowobfuscation class {class_name}$*"
        )
        lines.append(
            f"-keepclassmembers class {class_name}$* {{ *; }}"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("app/release-instrumentation-rules.pro"),
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    output = args.output if args.output.is_absolute() else repo_root / args.output
    expected = render_rules(repo_root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise ValueError(
                f"release instrumentation R8 boundary is stale: {output}; "
                "regenerate it after the Hilt compile"
            )
        print(f"Verified release instrumentation R8 boundary in {output}")
        return 0
    output.write_text(expected, encoding="utf-8")
    print(
        f"Generated {len(boundary_classes(repo_root))} R8 boundary classes in {output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
