[package]
name = "ripdpi-android-vpn-protect-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
android-support = { workspace = true }
jni = { workspace = true }
ripdpi-native-protect = { workspace = true }
tracing = { workspace = true }
