[package]
name = "ripdpi-strategy-ipv6"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
linkme = { workspace = true }
ripdpi-strategy-trait = { workspace = true }

[dev-dependencies]
ripdpi-strategy-config = { workspace = true }
ripdpi-strategy-registry = { workspace = true }
