-- Deterministic variants of zapret-tests.lua test_dissect/test_csum.
-- Run with the pinned nfqws2 backend, zapret-lib.lua and interception disabled.
assert(NFQWS2_COMPAT_VER == 6)
print('// Generated by native/zapret2/tests/packet_vectors.lua; do not edit.')
print('// Upstream ca950d838a0ee7dc32bb6ae5e65e54488c1bfe3b, test_dissect/test_csum.')
local function emit(name, dis, options)
    local raw = reconstruct_dissect(dis, options)
    assert(raw == reconstruct_dissect(dissect(raw), options), name)
    print('pub(super) const '..name..': &str = "'..string2hex(raw)..'";')
end
local tcp = {
    th_sport=49152, th_dport=443, th_seq=0xFFFFFFFE, th_ack=0x12345678,
    th_flags=24, th_win=4096, th_urp=0,
    options={{kind=1}, {kind=224,data='\xaa\xbb\xcc'}, {kind=1}, {kind=225,data='\x11\x22\x33'}}
}
local ip = {
    ip_tos=16, ip_id=0x1234, ip_off=0x4000, ip_ttl=64, ip_p=IPPROTO_TCP,
    ip_src=pton('192.0.2.10'), ip_dst=pton('198.51.100.20'), options='\1\1\0\0'
}
local ip6 = {
    ip6_flow=0x61234567, ip6_hlim=64,
    ip6_src=pton('2001:db8::10'), ip6_dst=pton('2001:db8::20')
}
local hop = {{type=IPPROTO_HOPOPTS,data='\1\4\0\0\0\0'}}
for _,case in ipairs({
    {'IPV4_TCP', {ip=ip,tcp=tcp,payload='abcdefg'}},
    {'IPV6_TCP', {ip6=ip6,tcp=tcp,payload='abcdefg'}},
    {'IPV6_HOP_TCP', {ip6=deepcopy(ip6),tcp=tcp,payload='abcdefg'}}
}) do
    local name, dis = case[1], deepcopy(case[2])
    if name=='IPV6_HOP_TCP' then dis.ip6.exthdr=hop end
    emit(name,dis)
    local first=deepcopy(dis); first.payload='ab'; emit(name..'_FIRST',first)
    local second=deepcopy(dis); second.payload='cdefg'; second.tcp.th_seq=0; emit(name..'_SECOND',second)
    local rewrite=deepcopy(dis); rewrite.payload='\0new\xff'; emit(name..'_REWRITE',rewrite)
    if name~='IPV6_HOP_TCP' then
        local fake=deepcopy(dis)
        if fake.ip then fake.ip.ip_ttl=3 else fake.ip6.ip6_hlim=3 end
        emit(name..'_LOW_TTL',fake)
    end
end
local udp={uh_sport=49152,uh_dport=443}
local ip_udp=deepcopy(ip); ip_udp.ip_p=IPPROTO_UDP
local ip6_udp=deepcopy(ip6); ip6_udp.exthdr=hop
for _,case in ipairs({
    {'IPV4_UDP',{ip=ip_udp,udp=udp,payload='abcdefg'}},
    {'IPV6_HOP_UDP',{ip6=ip6_udp,udp=udp,payload='abcdefg'}}
}) do
    emit(case[1],case[2])
    local rewrite=deepcopy(case[2]); rewrite.payload='\0new\xff'; emit(case[1]..'_REWRITE',rewrite)
    if case[1]=='IPV4_UDP' then
        rewrite.udp.uh_ulen=8+#rewrite.payload; rewrite.udp.uh_sum=0
        emit('IPV4_UDP_REWRITE_ZERO_SUM',rewrite,{keepsum=true})
    end
end
local ah=deepcopy(ip6_udp)
ah.exthdr[2]={type=IPPROTO_AH,data='\0\0\0\0\0\0\0\0\0\0'}
emit('IPV6_AH_UDP',{ip6=ah,udp=udp,payload='abcdefg'})
