//! Offline HTTP-injection classifier.
//!
//! Classifies a captured HTTP response against a static fingerprint table to
//! determine whether the response was injected by a middlebox, transparent
//! proxy, or captive-portal redirect — without performing any network I/O.

/// Verdict produced by [`classify_http_response`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InjectionVerdict {
    /// Response looks clean — no injection markers detected.
    Clean,
    /// A known injection fingerprint matched.  The inner `String` carries the
    /// fingerprint `id` (e.g. `"transparent-proxy-isp"`).
    Injected(String),
    /// Response is a redirect (3xx) whose `Location` header points to a
    /// captive-portal or operator block-page URL.
    RedirectToPortal,
    /// The TCP connection was reset after the request was sent (represented
    /// here as a sentinel status code 0 with an explicit error body).
    ConnectionResetAfterRequest,
}

/// How a fingerprint is expressed in the HTTP response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FingerprintKind {
    /// A specific HTTP header (name, substring of value) indicates a
    /// transparent proxy or middlebox inserted itself in the path.
    TransparentProxyHeader,
    /// A substring present in the response body marks an ISP block-page
    /// generated by a middlebox HTML injector.
    MiddleboxHtmlMarker,
    /// A 3xx redirect whose `Location` value matches a known operator
    /// captive-portal or block-page URL pattern.
    CaptiveRedirect,
}

/// A single statically-defined injection fingerprint.
pub struct HttpInjectionFingerprint {
    /// Stable identifier returned inside [`InjectionVerdict::Injected`].
    pub id: &'static str,
    /// How the fingerprint is expressed in the response.
    pub kind: FingerprintKind,
    /// The substring to look for (header value fragment or body fragment or
    /// Location URL prefix, depending on `kind`).
    pub marker: &'static str,
}

/// Built-in fingerprint table — one entry per [`FingerprintKind`] variant.
///
/// These are intentionally minimal offline anchors.  A richer runtime set is
/// maintained in `ripdpi-failure-classifier`; this table covers the three
/// structural injection classes needed for the diagnostic classifier.
pub static BUILTIN_FINGERPRINTS: &[HttpInjectionFingerprint] = &[
    // --- TransparentProxyHeader ---
    // Many ISP transparent caches insert a `Via` header that includes their
    // cache product name.  "nginx-cache-isp" is a representative marker.
    HttpInjectionFingerprint {
        id: "transparent-proxy-isp",
        kind: FingerprintKind::TransparentProxyHeader,
        marker: "nginx-cache-isp",
    },
    // --- MiddleboxHtmlMarker ---
    // Russian RKN-mandated block-pages frequently contain this phrase.
    HttpInjectionFingerprint {
        id: "ru-rkn-middlebox",
        kind: FingerprintKind::MiddleboxHtmlMarker,
        marker: "Доступ к ресурсу ограничен",
    },
    // --- CaptiveRedirect ---
    // A redirect whose Location starts with a known operator block-page
    // hostname pattern signals a captive-portal injection.
    HttpInjectionFingerprint {
        id: "captive-portal-redirect",
        kind: FingerprintKind::CaptiveRedirect,
        marker: "https://block.example/",
    },
];

/// Classify a captured HTTP response against [`BUILTIN_FINGERPRINTS`].
///
/// This function is pure and performs no I/O.
///
/// * `status`  — HTTP status code (use `0` to signal connection-reset).
/// * `headers` — response headers as `(name, value)` pairs; names are
///               compared case-insensitively.
/// * `body`    — response body as a UTF-8 string slice (pass an empty string
///               when the body is absent or binary).
pub fn classify_http_response(status: u16, headers: &[(String, String)], body: &str) -> InjectionVerdict {
    // Sentinel: caller signals a TCP reset with status 0.
    if status == 0 {
        return InjectionVerdict::ConnectionResetAfterRequest;
    }

    for fp in BUILTIN_FINGERPRINTS {
        match fp.kind {
            FingerprintKind::TransparentProxyHeader => {
                for (name, value) in headers {
                    if name.eq_ignore_ascii_case("via") && value.to_ascii_lowercase().contains(fp.marker) {
                        return InjectionVerdict::Injected(fp.id.to_string());
                    }
                }
            }
            FingerprintKind::MiddleboxHtmlMarker => {
                if body.contains(fp.marker) {
                    return InjectionVerdict::Injected(fp.id.to_string());
                }
            }
            FingerprintKind::CaptiveRedirect => {
                if (300..=399).contains(&status) {
                    for (name, value) in headers {
                        if name.eq_ignore_ascii_case("location") && value.starts_with(fp.marker) {
                            return InjectionVerdict::RedirectToPortal;
                        }
                    }
                }
            }
        }
    }

    InjectionVerdict::Clean
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hdr(name: &str, value: &str) -> (String, String) {
        (name.to_string(), value.to_string())
    }

    #[test]
    fn clean_200_no_markers_returns_clean() {
        let headers = vec![hdr("content-type", "text/html"), hdr("server", "nginx/1.24")];
        let body = "<html><body>Hello world</body></html>";
        assert_eq!(classify_http_response(200, &headers, body), InjectionVerdict::Clean);
    }

    #[test]
    fn via_header_with_nginx_cache_isp_returns_injected() {
        let headers = vec![hdr("content-type", "text/html"), hdr("via", "1.1 nginx-cache-isp (squid/4.14)")];
        let body = "<html><body>some page</body></html>";
        assert_eq!(
            classify_http_response(200, &headers, body),
            InjectionVerdict::Injected("transparent-proxy-isp".to_string())
        );
    }

    #[test]
    fn russian_rkn_body_marker_returns_injected() {
        let headers = vec![hdr("content-type", "text/html; charset=utf-8")];
        let body = "<html><body>Доступ к ресурсу ограничен по решению суда.</body></html>";
        assert_eq!(
            classify_http_response(200, &headers, body),
            InjectionVerdict::Injected("ru-rkn-middlebox".to_string())
        );
    }

    #[test]
    fn redirect_to_captive_portal_returns_redirect_to_portal() {
        let headers = vec![
            hdr("location", "https://block.example/notice?url=http%3A%2F%2Fexample.com"),
            hdr("content-length", "0"),
        ];
        assert_eq!(classify_http_response(302, &headers, ""), InjectionVerdict::RedirectToPortal);
    }

    #[test]
    fn status_zero_returns_connection_reset() {
        assert_eq!(classify_http_response(0, &[], ""), InjectionVerdict::ConnectionResetAfterRequest);
    }
}
