package com.poyka.ripdpi.core.codec

import com.poyka.ripdpi.core.RipDpiRelayConfig
import com.poyka.ripdpi.core.RipDpiRelayFinalmaskConfig
import com.poyka.ripdpi.data.normalizeRelayCongestionControl
import kotlinx.serialization.Serializable

@Serializable
internal data class NativeRelayFinalmaskConfig(
    val type: String = com.poyka.ripdpi.data.RelayFinalmaskTypeOff,
    val headerHex: String = "",
    val trailerHex: String = "",
    val randRange: String = "",
    val sudokuSeed: String = "",
    val fragmentPackets: Int = 0,
    val fragmentMinBytes: Int = 0,
    val fragmentMaxBytes: Int = 0,
)

@Serializable
internal data class NativeRelayConfig(
    val enabled: Boolean = false,
    val kind: String = "off",
    val profileId: String = "",
    val outboundBindIp: String = "",
    val server: String = "",
    val serverPort: Int = 443,
    val serverName: String = "",
    val realityPublicKey: String = "",
    val realityShortId: String = "",
    val vlessTransport: String = "reality_tcp",
    val xhttpPath: String = "",
    val xhttpHost: String = "",
    val cloudflareTunnelMode: String = com.poyka.ripdpi.data.RelayCloudflareTunnelModeConsumeExisting,
    val cloudflarePublishLocalOriginUrl: String = "",
    val cloudflareCredentialsRef: String = "",
    val chainEntryServer: String = "",
    val chainEntryPort: Int = 443,
    val chainEntryServerName: String = "",
    val chainEntryPublicKey: String = "",
    val chainEntryShortId: String = "",
    val chainEntryProfileId: String = "",
    val chainExitServer: String = "",
    val chainExitPort: Int = 443,
    val chainExitServerName: String = "",
    val chainExitPublicKey: String = "",
    val chainExitShortId: String = "",
    val chainExitProfileId: String = "",
    val masqueUrl: String = "",
    val masqueUseHttp2Fallback: Boolean = true,
    val masqueCloudflareGeohashEnabled: Boolean = false,
    val tuicZeroRtt: Boolean = false,
    val tuicCongestionControl: String = "bbr",
    val shadowTlsInnerProfileId: String = "",
    val naivePath: String = "",
    val localSocksHost: String = "127.0.0.1",
    val localSocksPort: Int = 11980,
    val udpEnabled: Boolean = false,
    val tcpFallbackEnabled: Boolean = true,
    val finalmask: NativeRelayFinalmaskConfig = NativeRelayFinalmaskConfig(),
)

internal object RelaySectionCodec {
    fun toModel(value: NativeRelayConfig): RipDpiRelayConfig =
        RipDpiRelayConfig(
            enabled = value.enabled,
            kind = value.kind,
            profileId = value.profileId,
            outboundBindIp = value.outboundBindIp,
            server = value.server,
            serverPort = value.serverPort,
            serverName = value.serverName,
            realityPublicKey = value.realityPublicKey,
            realityShortId = value.realityShortId,
            vlessTransport = value.vlessTransport,
            xhttpPath = value.xhttpPath,
            xhttpHost = value.xhttpHost,
            cloudflareTunnelMode = value.cloudflareTunnelMode,
            cloudflarePublishLocalOriginUrl = value.cloudflarePublishLocalOriginUrl,
            cloudflareCredentialsRef = value.cloudflareCredentialsRef,
            chainEntryServer = value.chainEntryServer,
            chainEntryPort = value.chainEntryPort,
            chainEntryServerName = value.chainEntryServerName,
            chainEntryPublicKey = value.chainEntryPublicKey,
            chainEntryShortId = value.chainEntryShortId,
            chainEntryProfileId = value.chainEntryProfileId,
            chainExitServer = value.chainExitServer,
            chainExitPort = value.chainExitPort,
            chainExitServerName = value.chainExitServerName,
            chainExitPublicKey = value.chainExitPublicKey,
            chainExitShortId = value.chainExitShortId,
            chainExitProfileId = value.chainExitProfileId,
            masqueUrl = value.masqueUrl,
            masqueUseHttp2Fallback = value.masqueUseHttp2Fallback,
            masqueCloudflareGeohashEnabled = value.masqueCloudflareGeohashEnabled,
            tuicZeroRtt = value.tuicZeroRtt,
            tuicCongestionControl = normalizeRelayCongestionControl(value.tuicCongestionControl),
            shadowTlsInnerProfileId = value.shadowTlsInnerProfileId,
            naivePath = value.naivePath,
            localSocksHost = value.localSocksHost,
            localSocksPort = value.localSocksPort,
            udpEnabled = value.udpEnabled,
            tcpFallbackEnabled = value.tcpFallbackEnabled,
            finalmask =
                RipDpiRelayFinalmaskConfig(
                    type = value.finalmask.type,
                    headerHex = value.finalmask.headerHex,
                    trailerHex = value.finalmask.trailerHex,
                    randRange = value.finalmask.randRange,
                    sudokuSeed = value.finalmask.sudokuSeed,
                    fragmentPackets = value.finalmask.fragmentPackets,
                    fragmentMinBytes = value.finalmask.fragmentMinBytes,
                    fragmentMaxBytes = value.finalmask.fragmentMaxBytes,
                ),
        )

    fun toNative(value: RipDpiRelayConfig): NativeRelayConfig =
        NativeRelayConfig(
            enabled = value.enabled,
            kind = value.kind,
            profileId = value.profileId,
            outboundBindIp = value.outboundBindIp,
            server = value.server,
            serverPort = value.serverPort,
            serverName = value.serverName,
            realityPublicKey = value.realityPublicKey,
            realityShortId = value.realityShortId,
            vlessTransport = value.vlessTransport,
            xhttpPath = value.xhttpPath,
            xhttpHost = value.xhttpHost,
            cloudflareTunnelMode = value.cloudflareTunnelMode,
            cloudflarePublishLocalOriginUrl = value.cloudflarePublishLocalOriginUrl,
            cloudflareCredentialsRef = value.cloudflareCredentialsRef,
            chainEntryServer = value.chainEntryServer,
            chainEntryPort = value.chainEntryPort,
            chainEntryServerName = value.chainEntryServerName,
            chainEntryPublicKey = value.chainEntryPublicKey,
            chainEntryShortId = value.chainEntryShortId,
            chainEntryProfileId = value.chainEntryProfileId,
            chainExitServer = value.chainExitServer,
            chainExitPort = value.chainExitPort,
            chainExitServerName = value.chainExitServerName,
            chainExitPublicKey = value.chainExitPublicKey,
            chainExitShortId = value.chainExitShortId,
            chainExitProfileId = value.chainExitProfileId,
            masqueUrl = value.masqueUrl,
            masqueUseHttp2Fallback = value.masqueUseHttp2Fallback,
            masqueCloudflareGeohashEnabled = value.masqueCloudflareGeohashEnabled,
            tuicZeroRtt = value.tuicZeroRtt,
            tuicCongestionControl = normalizeRelayCongestionControl(value.tuicCongestionControl),
            shadowTlsInnerProfileId = value.shadowTlsInnerProfileId,
            naivePath = value.naivePath,
            localSocksHost = value.localSocksHost,
            localSocksPort = value.localSocksPort,
            udpEnabled = value.udpEnabled,
            tcpFallbackEnabled = value.tcpFallbackEnabled,
            finalmask =
                NativeRelayFinalmaskConfig(
                    type = value.finalmask.type,
                    headerHex = value.finalmask.headerHex,
                    trailerHex = value.finalmask.trailerHex,
                    randRange = value.finalmask.randRange,
                    sudokuSeed = value.finalmask.sudokuSeed,
                    fragmentPackets = value.finalmask.fragmentPackets,
                    fragmentMinBytes = value.finalmask.fragmentMinBytes,
                    fragmentMaxBytes = value.finalmask.fragmentMaxBytes,
                ),
        )
}
