import com.android.build.api.dsl.ApplicationExtension
import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import com.android.build.api.variant.VariantOutputConfiguration
import com.android.build.gradle.internal.tasks.FinalizeBundleTask
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.io.File

plugins {
    id("com.android.application")
    id("ripdpi.android.native")
}

val moduleProguardRules = project.layout.projectDirectory.file("proguard-rules.pro").asFile
val r8DiagnosticsEnabled =
    providers.gradleProperty("ripdpi.r8Diagnostics").map(String::toBoolean).getOrElse(false)
val releaseR8DiagnosticsConfig = project.layout.buildDirectory.file("generated/r8/release-diagnostics.pro")

fun File.asProguardPath(): String = absolutePath.replace(File.separatorChar, '/')

if (r8DiagnosticsEnabled) {
    val diagnosticsConfig = releaseR8DiagnosticsConfig.get().asFile
    diagnosticsConfig.parentFile.mkdirs()
    diagnosticsConfig.writeText(
        """
        # Generated by ripdpi.android.application when -Pripdpi.r8Diagnostics=true.
        -printusage ${project.layout.buildDirectory.file("outputs/mapping/release/usage.txt").get().asFile.asProguardPath()}
        -printseeds ${project.layout.buildDirectory.file("outputs/mapping/release/seeds.txt").get().asFile.asProguardPath()}
        -printconfiguration ${project.layout.buildDirectory.file("outputs/mapping/release/configuration.txt").get().asFile.asProguardPath()}
        """.trimIndent() + "\n",
    )
}

extensions.configure<ApplicationExtension> {
    compileSdk = providers.gradleProperty("ripdpi.compileSdk").get().toInt()

    defaultConfig {
        minSdk = providers.gradleProperty("ripdpi.minSdk").get().toInt()
        targetSdk = providers.gradleProperty("ripdpi.targetSdk").get().toInt()
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"))
            if (moduleProguardRules.isFile) {
                proguardFiles(moduleProguardRules)
            }
            if (r8DiagnosticsEnabled) {
                proguardFiles(releaseR8DiagnosticsConfig.get().asFile)
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }

}

extensions.configure<ApplicationAndroidComponentsExtension> {
    onVariants(selector().all()) { variant ->
        val mainOutput =
            variant.outputs.firstOrNull { output ->
                output.outputType == VariantOutputConfiguration.OutputType.SINGLE
            } ?: return@onVariants

        val versionName =
            requireNotNull(mainOutput.versionName.orNull) {
                "versionName is required for artifact naming."
            }
        val versionCode = requireNotNull(mainOutput.versionCode.orNull) {
            "versionCode is required for artifact naming."
        }
        val buildTypeName = variant.buildType ?: "release"
        val artifactBaseName = "RIPDPI-$versionName-$versionCode-$buildTypeName"

        // AGP 9 no longer exposes APK file renaming on the public variant API.
        val bundleTaskName = variant.computeTaskName("sign", "Bundle")
        project.tasks.withType(FinalizeBundleTask::class.java).configureEach {
            if (name != bundleTaskName) return@configureEach
            finalBundleFile.set(
                project.layout.buildDirectory.file("outputs/bundle/${variant.name}/$artifactBaseName.aab"),
            )
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}
