import com.android.build.api.dsl.ApplicationExtension
import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import com.android.build.api.variant.FilterConfiguration
import com.android.build.api.variant.VariantOutputConfiguration
import com.android.build.gradle.internal.tasks.FinalizeBundleTask
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.io.File

val abiVersionMultipliers =
    mapOf(
        "armeabi-v7a" to 1,
        "arm64-v8a" to 2,
        "x86" to 3,
        "x86_64" to 4,
    )

plugins {
    id("com.android.application")
    id("ripdpi.android.native")
}

val moduleProguardRules =
    project.layout.projectDirectory
        .file("proguard-rules.pro")
        .asFile
val r8DiagnosticsEnabled =
    providers.gradleProperty("ripdpi.r8Diagnostics").map(String::toBoolean).getOrElse(false)
val releaseR8DiagnosticsConfig = project.layout.buildDirectory.file("generated/r8/release-diagnostics.pro")

fun File.asProguardPath(): String = absolutePath.replace(File.separatorChar, '/')

if (r8DiagnosticsEnabled) {
    val diagnosticsConfig = releaseR8DiagnosticsConfig.get().asFile
    diagnosticsConfig.parentFile.mkdirs()
    diagnosticsConfig.writeText(
        """
        # Generated by ripdpi.android.application when -Pripdpi.r8Diagnostics=true.
        -printusage ${project.layout.buildDirectory.file(
            "outputs/mapping/release/usage.txt",
        ).get().asFile.asProguardPath()}
        -printseeds ${project.layout.buildDirectory.file(
            "outputs/mapping/release/seeds.txt",
        ).get().asFile.asProguardPath()}
        -printconfiguration ${project.layout.buildDirectory.file(
            "outputs/mapping/release/configuration.txt",
        ).get().asFile.asProguardPath()}
        """.trimIndent() + "\n",
    )
}

extensions.configure<ApplicationExtension> {
    compileSdk = providers.gradleProperty("ripdpi.compileSdk").get().toInt()

    defaultConfig {
        minSdk = providers.gradleProperty("ripdpi.minSdk").get().toInt()
        targetSdk = providers.gradleProperty("ripdpi.targetSdk").get().toInt()
    }

    val abiSplitsEnabled = providers.gradleProperty("ripdpi.enableAbiSplits").map(String::toBoolean).getOrElse(true)
    splits {
        abi {
            isEnable = abiSplitsEnabled
            isUniversalApk = true
            reset()
            val nativeAbis = parseAbiList(providers.gradleProperty("ripdpi.nativeAbis").get())
            include(*nativeAbis.toTypedArray())
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"))
            if (moduleProguardRules.isFile) {
                proguardFiles(moduleProguardRules)
            }
            if (r8DiagnosticsEnabled) {
                proguardFiles(releaseR8DiagnosticsConfig.get().asFile)
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }
}

extensions.configure<ApplicationAndroidComponentsExtension> {
    onVariants(selector().all()) { variant ->
        variant.outputs.forEach { output ->
            val versionName = output.versionName.orNull ?: return@forEach
            val baseVersionCode = output.versionCode.orNull ?: return@forEach
            val buildTypeName = variant.buildType ?: "release"

            when (output.outputType) {
                VariantOutputConfiguration.OutputType.SINGLE,
                VariantOutputConfiguration.OutputType.UNIVERSAL,
                -> {
                    // Universal / single APK — keep base version code.
                    val artifactBaseName = "RIPDPI-$versionName-$baseVersionCode-$buildTypeName-universal"
                    val bundleTaskName = variant.computeTaskName("sign", "Bundle")
                    project.tasks.withType(FinalizeBundleTask::class.java).configureEach {
                        if (name != bundleTaskName) return@configureEach
                        finalBundleFile.set(
                            project.layout.buildDirectory.file(
                                "outputs/bundle/${variant.name}/$artifactBaseName.aab",
                            ),
                        )
                    }
                }

                VariantOutputConfiguration.OutputType.ONE_OF_MANY -> {
                    // Per-ABI APK — assign distinct version code.
                    val abiName =
                        output.filters
                            .firstOrNull { it.filterType == FilterConfiguration.FilterType.ABI }
                            ?.identifier
                    val multiplier = abiName?.let { abiVersionMultipliers[it] } ?: 0
                    output.versionCode.set(multiplier * 10_000_000 + baseVersionCode)
                }
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}
