[package]
name = "ripdpi-strategy-registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ripdpi-desync = { workspace = true }
ripdpi-strategy-http = { workspace = true }
ripdpi-strategy-trait = { workspace = true }
ripdpi-strategy-udp = { workspace = true }
ripdpi-strategy-window = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ripdpi-strategy-config = { workspace = true }
static_assertions = "1"
