[package]
name = "ripdpi-strategy-registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
lua-strategies = ["dep:ripdpi-strategy-lua", "ripdpi-strategy-lua/lua-strategies"]

[dependencies]
ripdpi-desync = { workspace = true }
ripdpi-strategy-config = { workspace = true }
ripdpi-strategy-core = { workspace = true }
ripdpi-strategy-http = { workspace = true }
ripdpi-strategy-ipv6 = { workspace = true }
ripdpi-strategy-lua = { workspace = true, optional = true }
ripdpi-strategy-trait = { workspace = true }
ripdpi-strategy-udp = { workspace = true }
ripdpi-strategy-window = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
static_assertions = "1"
