package com.poyka.ripdpi.ui.screens.config

import com.poyka.ripdpi.data.Mode

internal data class ModeEditorActions(
    val onBack: () -> Unit,
    val onCancel: () -> Unit,
    val onModeSelected: (Mode) -> Unit,
    val onDnsIpChanged: (String) -> Unit,
    val onProxyIpChanged: (String) -> Unit,
    val onProxyPortChanged: (String) -> Unit,
    val onMaxConnectionsChanged: (String) -> Unit,
    val onBufferSizeChanged: (String) -> Unit,
    val onChainDslChanged: (String) -> Unit,
    val onDefaultTtlChanged: (String) -> Unit,
    val onCommandLineEnabledChanged: (Boolean) -> Unit,
    val onCommandLineArgsChanged: (String) -> Unit,
    val onRelayEnabledChanged: (Boolean) -> Unit,
    val onRelayKindChanged: (String) -> Unit,
    val onRelayProfileIdChanged: (String) -> Unit,
    val onRelayPresetSelected: (String) -> Unit,
    val onRelayServerChanged: (String) -> Unit,
    val onRelayServerPortChanged: (String) -> Unit,
    val onRelayServerNameChanged: (String) -> Unit,
    val onRelayRealityPublicKeyChanged: (String) -> Unit,
    val onRelayRealityShortIdChanged: (String) -> Unit,
    val onRelayVlessTransportChanged: (String) -> Unit,
    val onRelayXhttpPathChanged: (String) -> Unit,
    val onRelayXhttpHostChanged: (String) -> Unit,
    val onRelayXhttpModeChanged: (String) -> Unit,
    val onRelayCloudflareTunnelModeChanged: (String) -> Unit,
    val onRelayCloudflarePublishLocalOriginUrlChanged: (String) -> Unit,
    val onRelayCloudflareCredentialsRefChanged: (String) -> Unit,
    val onRelayCloudflareTunnelTokenChanged: (String) -> Unit,
    val onRelayCloudflareTunnelCredentialsJsonChanged: (String) -> Unit,
    val onRelayVlessUuidChanged: (String) -> Unit,
    val onRelayAnyTlsPasswordChanged: (String) -> Unit,
    val onRelayHysteriaPasswordChanged: (String) -> Unit,
    val onRelayHysteriaSalamanderKeyChanged: (String) -> Unit,
    val onRelayChainHopProfileIdChanged: (Int, String) -> Unit,
    val onRelayChainHopAdded: () -> Unit,
    val onRelayChainHopRemoved: (Int) -> Unit,
    val onRelayChainHopMoved: (Int, Int) -> Unit,
    val onRelayMasqueUrlChanged: (String) -> Unit,
    val onRelayMasqueAuthModeChanged: (String) -> Unit,
    val onRelayMasqueAuthTokenChanged: (String) -> Unit,
    val onRelayMasqueClientCertificateChainPemChanged: (String) -> Unit,
    val onRelayMasqueClientPrivateKeyPemChanged: (String) -> Unit,
    val onRelayMasqueUseHttp2FallbackChanged: (Boolean) -> Unit,
    val onRelayMasqueCloudflareGeohashEnabledChanged: (Boolean) -> Unit,
    val onRelayMasqueImportCertificateChainClicked: () -> Unit,
    val onRelayMasqueImportPrivateKeyClicked: () -> Unit,
    val onRelayMasqueImportPkcs12Clicked: () -> Unit,
    val onRelayTuicUuidChanged: (String) -> Unit,
    val onRelayTuicPasswordChanged: (String) -> Unit,
    val onRelayTuicZeroRttChanged: (Boolean) -> Unit,
    val onRelayTuicCongestionControlChanged: (String) -> Unit,
    val onRelayShadowTlsPasswordChanged: (String) -> Unit,
    val onRelayShadowTlsInnerProfileIdChanged: (String) -> Unit,
    val onRelayNaiveUsernameChanged: (String) -> Unit,
    val onRelayNaivePasswordChanged: (String) -> Unit,
    val onRelayNaivePathChanged: (String) -> Unit,
    val onRelayPtBridgeLineChanged: (String) -> Unit,
    val onRelayWebTunnelUrlChanged: (String) -> Unit,
    val onRelaySnowflakeBrokerUrlChanged: (String) -> Unit,
    val onRelaySnowflakeFrontDomainChanged: (String) -> Unit,
    val onRelayFinalmaskTypeChanged: (String) -> Unit,
    val onRelayFinalmaskHeaderHexChanged: (String) -> Unit,
    val onRelayFinalmaskTrailerHexChanged: (String) -> Unit,
    val onRelayFinalmaskRandRangeChanged: (String) -> Unit,
    val onRelayFinalmaskSudokuSeedChanged: (String) -> Unit,
    val onRelayFinalmaskFragmentPacketsChanged: (String) -> Unit,
    val onRelayFinalmaskFragmentMinBytesChanged: (String) -> Unit,
    val onRelayFinalmaskFragmentMaxBytesChanged: (String) -> Unit,
    val onRelayUdpEnabledChanged: (Boolean) -> Unit,
    val onRelayLocalSocksPortChanged: (String) -> Unit,
    val onSave: () -> Unit,
)

internal val NoOpModeEditorActions =
    ModeEditorActions(
        onBack = {},
        onCancel = {},
        onModeSelected = {},
        onDnsIpChanged = {},
        onProxyIpChanged = {},
        onProxyPortChanged = {},
        onMaxConnectionsChanged = {},
        onBufferSizeChanged = {},
        onChainDslChanged = {},
        onDefaultTtlChanged = {},
        onCommandLineEnabledChanged = {},
        onCommandLineArgsChanged = {},
        onRelayEnabledChanged = {},
        onRelayKindChanged = {},
        onRelayProfileIdChanged = {},
        onRelayPresetSelected = {},
        onRelayServerChanged = {},
        onRelayServerPortChanged = {},
        onRelayServerNameChanged = {},
        onRelayRealityPublicKeyChanged = {},
        onRelayRealityShortIdChanged = {},
        onRelayVlessTransportChanged = {},
        onRelayXhttpPathChanged = {},
        onRelayXhttpHostChanged = {},
        onRelayXhttpModeChanged = {},
        onRelayCloudflareTunnelModeChanged = {},
        onRelayCloudflarePublishLocalOriginUrlChanged = {},
        onRelayCloudflareCredentialsRefChanged = {},
        onRelayCloudflareTunnelTokenChanged = {},
        onRelayCloudflareTunnelCredentialsJsonChanged = {},
        onRelayVlessUuidChanged = {},
        onRelayAnyTlsPasswordChanged = {},
        onRelayHysteriaPasswordChanged = {},
        onRelayHysteriaSalamanderKeyChanged = {},
        onRelayChainHopProfileIdChanged = { _, _ -> },
        onRelayChainHopAdded = {},
        onRelayChainHopRemoved = {},
        onRelayChainHopMoved = { _, _ -> },
        onRelayMasqueUrlChanged = {},
        onRelayMasqueAuthModeChanged = {},
        onRelayMasqueAuthTokenChanged = {},
        onRelayMasqueClientCertificateChainPemChanged = {},
        onRelayMasqueClientPrivateKeyPemChanged = {},
        onRelayMasqueUseHttp2FallbackChanged = {},
        onRelayMasqueCloudflareGeohashEnabledChanged = {},
        onRelayMasqueImportCertificateChainClicked = {},
        onRelayMasqueImportPrivateKeyClicked = {},
        onRelayMasqueImportPkcs12Clicked = {},
        onRelayTuicUuidChanged = {},
        onRelayTuicPasswordChanged = {},
        onRelayTuicZeroRttChanged = {},
        onRelayTuicCongestionControlChanged = {},
        onRelayShadowTlsPasswordChanged = {},
        onRelayShadowTlsInnerProfileIdChanged = {},
        onRelayNaiveUsernameChanged = {},
        onRelayNaivePasswordChanged = {},
        onRelayNaivePathChanged = {},
        onRelayPtBridgeLineChanged = {},
        onRelayWebTunnelUrlChanged = {},
        onRelaySnowflakeBrokerUrlChanged = {},
        onRelaySnowflakeFrontDomainChanged = {},
        onRelayFinalmaskTypeChanged = {},
        onRelayFinalmaskHeaderHexChanged = {},
        onRelayFinalmaskTrailerHexChanged = {},
        onRelayFinalmaskRandRangeChanged = {},
        onRelayFinalmaskSudokuSeedChanged = {},
        onRelayFinalmaskFragmentPacketsChanged = {},
        onRelayFinalmaskFragmentMinBytesChanged = {},
        onRelayFinalmaskFragmentMaxBytesChanged = {},
        onRelayUdpEnabledChanged = {},
        onRelayLocalSocksPortChanged = {},
        onSave = {},
    )
